<?php  //[STAMP] 402f32e59aeed4ce5f07b693f0231713
namespace dlds\mlm\tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use dlds\mlm\tests\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
